# Generated by Django 3.0.5 on 2023-10-19 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_nd',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('OTHER', 'OTHER')], default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fatherName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='hobby',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_nd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='motherName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pastMediacalRec',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('OTHER', 'OTHER')], default='Gujrat', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 19, 18, 32, 31, 519902)),
        ),
    ]
