# Generated by Django 3.0.5 on 2023-10-19 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20231019_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='language',
            field=models.CharField(choices=[('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('MARATHI', 'MARATHI'), ('OTHER', 'OTHER')], default='HINDI', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 19, 18, 59, 4, 544848)),
        ),
    ]
