# Generated by Django 3.0.5 on 2023-10-20 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20231019_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 11, 5, 58, 311748)),
        ),
    ]
