# Generated by Django 3.0.5 on 2023-10-20 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20231020_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 16, 17, 35, 241622)),
        ),
    ]
