# Generated by Django 3.0.5 on 2023-10-21 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20231020_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 21, 10, 26, 34, 869522)),
        ),
    ]
