# Generated by Django 3.0.5 on 2023-10-22 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20231021_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 12, 41, 22, 768291)),
        ),
    ]
